//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDate", ReplyAction="http://tempuri.org/IService1/GetDateResponse")]
        string GetDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDate", ReplyAction="http://tempuri.org/IService1/GetDateResponse")]
        System.Threading.Tasks.Task<string> GetDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCompagnyActive", ReplyAction="http://tempuri.org/IService1/GetCompagnyActiveResponse")]
        System.Collections.Generic.Dictionary<string, int> GetCompagnyActive(string comp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCompagnyActive", ReplyAction="http://tempuri.org/IService1/GetCompagnyActiveResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetCompagnyActiveAsync(string comp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference1.IService1>, Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetDate() {
            return base.Channel.GetDate();
        }
        
        public System.Threading.Tasks.Task<string> GetDateAsync() {
            return base.Channel.GetDateAsync();
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetCompagnyActive(string comp) {
            return base.Channel.GetCompagnyActive(comp);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetCompagnyActiveAsync(string comp) {
            return base.Channel.GetCompagnyActiveAsync(comp);
        }
    }
}
